"""MicroPython firmware proxy + main.py generation.

Not a target plugin: like CircuitPython, the interpreter is stock and the
design only produces the script that runs on it. Release images live on
micropython.org, one per port board (`ESP32_GENERIC`, `ESP32_GENERIC_S3`,
...) with a variant suffix for PSRAM or small-flash builds, and the site
publishes no index API: each board's download page lists the firmware
links, so the newest stable is read off that page.

Every library board maps to a generic port image. MicroPython addresses
pins by bare GPIO number, so nothing depends on a board-specific build;
the variant only tracks PSRAM and flash size. The ESP32 classic image
flashes at 0x1000, every other port at 0x0.
"""
from __future__ import annotations

import re

from fastapi import APIRouter, HTTPException, Response
from pydantic import ValidationError

from wirestudio.errors import describe
from wirestudio.generate.micropython_gen import generate_code
from wirestudio.library import Library, LibraryBoard
from wirestudio.model import Design

_DOWNLOAD_BASE = "https://micropython.org"

# chip_variant -> (port board id, flash offset)
_PORTS: dict[str, tuple[str, int]] = {
    "esp32": ("ESP32_GENERIC", 0x1000),
    "esp32s3": ("ESP32_GENERIC_S3", 0x0),
    "esp32c3": ("ESP32_GENERIC_C3", 0x0),
    "esp32c6": ("ESP32_GENERIC_C6", 0x0),
    "esp8266": ("ESP8266_GENERIC", 0x0),
}

# Boards whose chip carries PSRAM the generic image can use.
_SPIRAM_BOARDS = {"esp32-wrover-cam", "esp32cam-ai-thinker"}

_FIRMWARE_TIMEOUT = 120  # seconds; images are 1.5-2 MB

_LINK = re.compile(
    r'href="(?P<path>/resources/firmware/(?P<board>[A-Z0-9_]+?)'
    r'(?:-(?P<variant>[A-Z0-9_]+))?-(?P<date>\d{8})-v(?P<version>\d+\.\d+\.\d+)\.bin)"'
)


def image_for(board: LibraryBoard) -> tuple[str, str | None, int] | None:
    """(port board id, variant or None, flash offset) for a library board."""
    port = _PORTS.get(board.chip_variant)
    if port is None:
        return None
    board_id, offset = port
    variant = None
    if board.id in _SPIRAM_BOARDS:
        variant = "SPIRAM"
    elif board.chip_variant == "esp8266" and (board.flash_size_mb or 0) <= 1:
        variant = "FLASH_1M"
    return board_id, variant, offset


def _fetch_page(board_id: str) -> str:
    import httpx

    resp = httpx.get(f"{_DOWNLOAD_BASE}/download/{board_id}/", timeout=15, follow_redirects=True)
    resp.raise_for_status()
    return resp.text


def latest_stable(board_id: str, variant: str | None) -> tuple[str, str]:
    """(download URL, version) of the newest stable build listed on the
    board's download page. Preview builds carry `-preview` in the version
    and do not match."""
    found: list[tuple[tuple[int, ...], str, str, str]] = []
    for m in _LINK.finditer(_fetch_page(board_id)):
        if m["board"] != board_id or m["variant"] != variant:
            continue
        ver = tuple(int(x) for x in m["version"].split("."))
        found.append((ver, m["date"], m["path"], m["version"]))
    if not found:
        raise LookupError(f"no stable build listed for {board_id}{'-' + variant if variant else ''}")
    _, _, path, version = max(found)
    return f"{_DOWNLOAD_BASE}{path}", version


def _fetch_firmware(url: str) -> bytes:
    import httpx

    resp = httpx.get(url, timeout=_FIRMWARE_TIMEOUT, follow_redirects=True)
    resp.raise_for_status()
    return resp.content


def firmware_status(lib: Library) -> dict:
    boards = {b.id: image_for(b) for b in lib.list_boards()}
    boards = {k: v for k, v in boards.items() if v is not None}
    try:
        _, version = latest_stable("ESP32_GENERIC", None)
        available, reason = True, None
    except Exception as e:
        version, available, reason = None, False, f"release lookup failed: {describe(e)}"
    return {
        "available": available,
        "version": version,
        "boards": sorted(boards),
        "images": {b: (f"{img}-{var}" if var else img) for b, (img, var, _) in sorted(boards.items())},
        "offsets": {b: off for b, (_, _, off) in sorted(boards.items())},
        "reason": reason,
    }


def _pin_num(pin: object) -> str | None:
    s = str(pin or "")
    return s.removeprefix("GPIO") if s.startswith("GPIO") else None


def starter_code(board: LibraryBoard) -> str:
    """A dependency-free main.py from the board's library metadata: Vext
    power-up, LED blink, I2C scan on the default bus."""
    onboard = board.onboard_peripherals or {}
    led = _pin_num((onboard.get("led") or {}).get("pin"))
    vext = onboard.get("vext") or {}
    vext_pin = _pin_num(vext.get("pin"))
    i2c = (board.default_buses or {}).get("i2c") or {}
    sda, scl = _pin_num(i2c.get("sda")), _pin_num(i2c.get("scl"))

    lines: list[str] = [
        f'"""{board.name} -- MicroPython starter, generated by wirestudio.',
        "",
        "Copy this file to the board as main.py (the flash dialog pushes it over",
        "serial; `mpremote cp main.py :` does the same). Output appears on the",
        "REPL at 115200 baud.",
    ]
    if onboard:
        lines += ["", "Onboard peripherals (from the wirestudio board library):"]
        for key, params in onboard.items():
            lines.append(f"  {key}: {params}")
    lines += ['"""', "import time", "", "from machine import Pin, SoftI2C", ""]

    if vext_pin:
        level = 0 if vext.get("inverted") else 1
        lines += [
            "",
            f"# Vext gates the onboard peripherals ({'active low' if vext.get('inverted') else 'active high'}) -- switch it on.",
            f"Pin({vext_pin}, Pin.OUT).value({level})",
            "",
        ]

    if led:
        lines += ["", f"# Onboard LED (GPIO{led} in the wirestudio board library).", f"led = Pin({led}, Pin.OUT)", ""]

    if sda and scl:
        lines += [
            "",
            f"# Default I2C bus (SDA=GPIO{sda}, SCL=GPIO{scl}): scan for devices.",
            "try:",
            f"    i2c = SoftI2C(scl=Pin({scl}), sda=Pin({sda}), freq=400000)",
            '    print("I2C scan:", [hex(a) for a in i2c.scan()])',
            "except Exception as e:",
            '    print("I2C scan failed:", e)',
            "",
        ]

    lines += ["", "n = 0", "while True:"]
    if led:
        lines += ["    led.value(not led.value())"]
    lines += ['    print("heartbeat", n)', "    n += 1", "    time.sleep(1)", ""]
    return "\n".join(lines)


def router(lib: Library) -> APIRouter:
    router = APIRouter(tags=["micropython"])

    def _entry(board: str) -> tuple[LibraryBoard, tuple[str, str | None, int]]:
        try:
            lib_board = lib.board(board)
        except FileNotFoundError as e:
            raise HTTPException(status_code=404, detail=str(e)) from e
        img = image_for(lib_board)
        if img is None:
            raise HTTPException(status_code=422, detail=f"no MicroPython port for chip '{lib_board.chip_variant}'")
        return lib_board, img

    @router.get("/firmware/status")
    def micropython_firmware_status() -> dict:
        return firmware_status(lib)

    # No return annotation: `from __future__ import annotations` turns it
    # into a string OpenAPI generation can't resolve.
    @router.get("/firmware", response_class=Response)
    def micropython_firmware(board: str):
        _, (board_id, variant, offset) = _entry(board)
        try:
            url, version = latest_stable(board_id, variant)
            data = _fetch_firmware(url)
        except Exception as e:
            raise HTTPException(status_code=502, detail=f"could not fetch firmware: {describe(e)}") from e
        return Response(
            content=data,
            media_type="application/octet-stream",
            headers={
                "X-Flash-Offset": str(offset),
                "X-Firmware-Version": version,
                "Content-Disposition": f'attachment; filename="{url.rsplit("/", 1)[-1]}"',
            },
        )

    @router.post("/code")
    def micropython_design_code(design: dict) -> dict:
        """main.py generated from the design: per-component driver init
        from the library's `micropython:` fragments, plus the mip specs
        of the drivers to install."""
        try:
            d = Design.model_validate(design)
        except ValidationError as e:
            raise HTTPException(status_code=422, detail=e.errors()) from e
        try:
            return generate_code(d, lib)
        except FileNotFoundError as e:
            raise HTTPException(status_code=404, detail=str(e)) from e

    @router.get("/code", response_class=Response)
    def micropython_code(board: str):
        lib_board, _ = _entry(board)
        return Response(
            content=starter_code(lib_board),
            media_type="text/x-python",
            headers={"Content-Disposition": 'attachment; filename="main.py"'},
        )

    return router
