// Generated by wirestudio (lorawan target). Do not edit by hand.
// Device: dev1
// Board:  ttgo-t-beam (esp32)
// Radio:  SX1276  |  Region US915 sub-band 2
//
// RadioLib + LoRaWAN_ESP32. NVS keeps DevNonces + session across reboots (the
// dominant cause of OTAA re-join rejection). When NVS is empty, persist.manage()
// prompts for band/sub-band + keys over serial -- the host-driven provisioning
// hook. The uplink payload is packed big-endian from a field spec shared with
// the ChirpStack decodeUplink codec on the device profile.

#include <RadioLib.h>
#include <LoRaWAN_ESP32.h>
#include <Wire.h>

// SX1276 wiring on this board: NSS=18, IRQ=26, RST=23, DIO1=RADIOLIB_NC.
SX1276 radio = new Module(18, 26, 23, RADIOLIB_NC);

LoRaWANNode* node;

// Survives deep sleep / soft reset (cleared on power-on); a coarse boot counter.
RTC_DATA_ATTR uint16_t bootCount = 0;

#define XPOWERS_CHIP_AXP192
#include "XPowersLib.h"
XPowersPMU power;            // AXP192 PMIC: gates the GPS + LoRa rails, reports battery
uint16_t batteryMv = 0;
#include <TinyGPS++.h>
TinyGPSPlus gps;
HardwareSerial GPSSerial(1);

// Pinned LoRaWAN parameters. The gateway is US915 sub-band 2; a mismatch makes
// the device transmit joins on channels the gateway never hears.
static const char*    WS_REGION   = "US915";
static const uint8_t  WS_SUBBAND  = 2;
static const uint64_t WS_JOIN_EUI = 0x0000000000000000ULL;

void setup() {
  Serial.begin(115200);
  bootCount++;
  Serial.printf("wirestudio lorawan: %s sub-band %u joinEUI %016llX\n",
                WS_REGION, WS_SUBBAND, (unsigned long long) WS_JOIN_EUI);
  Wire.begin(21, 22);
  Wire.setTimeOut(50);
if (power.begin(Wire, AXP192_SLAVE_ADDRESS, 21, 22)) {
  power.setLDO2Voltage(3300); power.enableLDO2();  // LoRa rail
  power.setLDO3Voltage(3300); power.enableLDO3();  // GPS rail
  power.enableBattDetection();
  power.enableBattVoltageMeasure();
  Serial.println("AXP192: LoRa + GPS rails enabled");
} else {
  Serial.println("AXP192 init failed (battery/GPS telemetry unavailable)");
}

  GPSSerial.begin(9600, SERIAL_8N1, 34, 12);

  int16_t state = radio.begin();
  if (state != RADIOLIB_ERR_NONE) {
    Serial.printf("radio.begin() failed: %d\n", state);
  }
  node = persist.manage(&radio);

  if (node->isActivated()) {
    Serial.println("JOINED: OTAA session active");
  } else {
    Serial.println("JOIN FAILED: not activated (check keys + gateway coverage; retries on reboot)");
  }
  // US915 DR0 (SF10) caps the app payload at 11 bytes; this 19-byte
  // payload needs at least DR1. ADR tunes the rate from here.
  node->setDatarate(1);
}

void loop() {
  // Host command channel: "wipe" clears stored provisioning + session (e.g. to
  // recover from an offline test's throwaway keys) and reboots to re-provision.
  if (Serial.available()) {
    Serial.setTimeout(100);
    String cmd = Serial.readStringUntil('\n');
    cmd.trim();
    if (cmd == "wipe") {
      Serial.println("wiping provisioning + session; rebooting...");
      persist.wipe();
      delay(200);
      ESP.restart();
    }
  }

  // Sensors + OLED refresh every iteration, independent of the LoRaWAN join,
  // so you get live feedback even with no gateway in range. The uplink (and a
  // re-join retry) run on a 60s cadence.
batteryMv = power.getBattVoltage();
while (GPSSerial.available()) gps.encode(GPSSerial.read());  // keep the fix current

  static unsigned long lastTx = 0;
  if (lastTx == 0 || millis() - lastTx >= 60000) {
    lastTx = millis();

    if (!node->isActivated()) {
      Serial.println("not joined -- retrying OTAA (sensors still live above)");
      node->activateOTAA();
      persist.saveSession(node);
    }
    if (node->isActivated()) {
      // Payload packed big-endian from the generated field spec (codec.py),
      // in lockstep with the ChirpStack decodeUplink codec on the profile.
      uint8_t payload[19];
  uint32_t _v_uptime_s = (uint32_t)(millis() / 1000UL);
  payload[0] = (uint8_t)(_v_uptime_s >> 24);
  payload[1] = (uint8_t)(_v_uptime_s >> 16);
  payload[2] = (uint8_t)(_v_uptime_s >> 8);
  payload[3] = (uint8_t)(_v_uptime_s);
  uint16_t _v_boot_count = bootCount;
  payload[4] = (uint8_t)(_v_boot_count >> 8);
  payload[5] = (uint8_t)(_v_boot_count);
  int32_t _v_lat = (int32_t)(gps.location.lat() * 10000000.0);
  payload[6] = (uint8_t)(_v_lat >> 24);
  payload[7] = (uint8_t)(_v_lat >> 16);
  payload[8] = (uint8_t)(_v_lat >> 8);
  payload[9] = (uint8_t)(_v_lat);
  int32_t _v_lon = (int32_t)(gps.location.lng() * 10000000.0);
  payload[10] = (uint8_t)(_v_lon >> 24);
  payload[11] = (uint8_t)(_v_lon >> 16);
  payload[12] = (uint8_t)(_v_lon >> 8);
  payload[13] = (uint8_t)(_v_lon);
  int16_t _v_alt_m = (int16_t)gps.altitude.meters();
  payload[14] = (uint8_t)(_v_alt_m >> 8);
  payload[15] = (uint8_t)(_v_alt_m);
  uint8_t _v_sats = (uint8_t)gps.satellites.value();
  payload[16] = (uint8_t)(_v_sats);
  uint16_t _v_batt_mv = batteryMv;
  payload[17] = (uint8_t)(_v_batt_mv >> 8);
  payload[18] = (uint8_t)(_v_batt_mv);
      int16_t state = node->sendReceive(payload, sizeof(payload));
      Serial.printf("uplink: RadioLib state %d\n", state);
      persist.saveSession(node);
    }
  }
  delay(500);
}
